// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImageStream.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ImageStream_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ImageStream_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ImageStream_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ImageStream_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ImageStream_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_ImageStream_2eproto_metadata_getter(int index);
namespace CVImageService {
class ImageMessage;
struct ImageMessageDefaultTypeInternal;
extern ImageMessageDefaultTypeInternal _ImageMessage_default_instance_;
}  // namespace CVImageService
PROTOBUF_NAMESPACE_OPEN
template<> ::CVImageService::ImageMessage* Arena::CreateMaybeMessage<::CVImageService::ImageMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace CVImageService {

// ===================================================================

class ImageMessage PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CVImageService.ImageMessage) */ {
 public:
  inline ImageMessage() : ImageMessage(nullptr) {}
  virtual ~ImageMessage();
  explicit constexpr ImageMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ImageMessage(const ImageMessage& from);
  ImageMessage(ImageMessage&& from) noexcept
    : ImageMessage() {
    *this = ::std::move(from);
  }

  inline ImageMessage& operator=(const ImageMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ImageMessage& operator=(ImageMessage&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ImageMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const ImageMessage* internal_default_instance() {
    return reinterpret_cast<const ImageMessage*>(
               &_ImageMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ImageMessage& a, ImageMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(ImageMessage* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ImageMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ImageMessage* New() const final {
    return CreateMaybeMessage<ImageMessage>(nullptr);
  }

  ImageMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ImageMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ImageMessage& from);
  void MergeFrom(const ImageMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ImageMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CVImageService.ImageMessage";
  }
  protected:
  explicit ImageMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_ImageStream_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommandFieldNumber = 1,
    kEnCodeBuffFieldNumber = 6,
    kRowFieldNumber = 2,
    kColumFieldNumber = 3,
    kTypeFieldNumber = 4,
    kChannelFieldNumber = 5,
  };
  // string Command = 1;
  void clear_command();
  const std::string& command() const;
  void set_command(const std::string& value);
  void set_command(std::string&& value);
  void set_command(const char* value);
  void set_command(const char* value, size_t size);
  std::string* mutable_command();
  std::string* release_command();
  void set_allocated_command(std::string* command);
  private:
  const std::string& _internal_command() const;
  void _internal_set_command(const std::string& value);
  std::string* _internal_mutable_command();
  public:

  // bytes EnCodeBuff = 6;
  void clear_encodebuff();
  const std::string& encodebuff() const;
  void set_encodebuff(const std::string& value);
  void set_encodebuff(std::string&& value);
  void set_encodebuff(const char* value);
  void set_encodebuff(const void* value, size_t size);
  std::string* mutable_encodebuff();
  std::string* release_encodebuff();
  void set_allocated_encodebuff(std::string* encodebuff);
  private:
  const std::string& _internal_encodebuff() const;
  void _internal_set_encodebuff(const std::string& value);
  std::string* _internal_mutable_encodebuff();
  public:

  // int32 row = 2;
  void clear_row();
  ::PROTOBUF_NAMESPACE_ID::int32 row() const;
  void set_row(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_row() const;
  void _internal_set_row(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 colum = 3;
  void clear_colum();
  ::PROTOBUF_NAMESPACE_ID::int32 colum() const;
  void set_colum(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_colum() const;
  void _internal_set_colum(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 type = 4;
  void clear_type();
  ::PROTOBUF_NAMESPACE_ID::int32 type() const;
  void set_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_type() const;
  void _internal_set_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 channel = 5;
  void clear_channel();
  ::PROTOBUF_NAMESPACE_ID::int32 channel() const;
  void set_channel(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_channel() const;
  void _internal_set_channel(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:CVImageService.ImageMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr command_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr encodebuff_;
  ::PROTOBUF_NAMESPACE_ID::int32 row_;
  ::PROTOBUF_NAMESPACE_ID::int32 colum_;
  ::PROTOBUF_NAMESPACE_ID::int32 type_;
  ::PROTOBUF_NAMESPACE_ID::int32 channel_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ImageStream_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ImageMessage

// string Command = 1;
inline void ImageMessage::clear_command() {
  command_.ClearToEmpty();
}
inline const std::string& ImageMessage::command() const {
  // @@protoc_insertion_point(field_get:CVImageService.ImageMessage.Command)
  return _internal_command();
}
inline void ImageMessage::set_command(const std::string& value) {
  _internal_set_command(value);
  // @@protoc_insertion_point(field_set:CVImageService.ImageMessage.Command)
}
inline std::string* ImageMessage::mutable_command() {
  // @@protoc_insertion_point(field_mutable:CVImageService.ImageMessage.Command)
  return _internal_mutable_command();
}
inline const std::string& ImageMessage::_internal_command() const {
  return command_.Get();
}
inline void ImageMessage::_internal_set_command(const std::string& value) {
  
  command_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ImageMessage::set_command(std::string&& value) {
  
  command_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:CVImageService.ImageMessage.Command)
}
inline void ImageMessage::set_command(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  command_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:CVImageService.ImageMessage.Command)
}
inline void ImageMessage::set_command(const char* value,
    size_t size) {
  
  command_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:CVImageService.ImageMessage.Command)
}
inline std::string* ImageMessage::_internal_mutable_command() {
  
  return command_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ImageMessage::release_command() {
  // @@protoc_insertion_point(field_release:CVImageService.ImageMessage.Command)
  return command_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ImageMessage::set_allocated_command(std::string* command) {
  if (command != nullptr) {
    
  } else {
    
  }
  command_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), command,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:CVImageService.ImageMessage.Command)
}

// int32 row = 2;
inline void ImageMessage::clear_row() {
  row_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageMessage::_internal_row() const {
  return row_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageMessage::row() const {
  // @@protoc_insertion_point(field_get:CVImageService.ImageMessage.row)
  return _internal_row();
}
inline void ImageMessage::_internal_set_row(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  row_ = value;
}
inline void ImageMessage::set_row(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_row(value);
  // @@protoc_insertion_point(field_set:CVImageService.ImageMessage.row)
}

// int32 colum = 3;
inline void ImageMessage::clear_colum() {
  colum_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageMessage::_internal_colum() const {
  return colum_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageMessage::colum() const {
  // @@protoc_insertion_point(field_get:CVImageService.ImageMessage.colum)
  return _internal_colum();
}
inline void ImageMessage::_internal_set_colum(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  colum_ = value;
}
inline void ImageMessage::set_colum(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_colum(value);
  // @@protoc_insertion_point(field_set:CVImageService.ImageMessage.colum)
}

// int32 type = 4;
inline void ImageMessage::clear_type() {
  type_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageMessage::_internal_type() const {
  return type_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageMessage::type() const {
  // @@protoc_insertion_point(field_get:CVImageService.ImageMessage.type)
  return _internal_type();
}
inline void ImageMessage::_internal_set_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  type_ = value;
}
inline void ImageMessage::set_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:CVImageService.ImageMessage.type)
}

// int32 channel = 5;
inline void ImageMessage::clear_channel() {
  channel_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageMessage::_internal_channel() const {
  return channel_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageMessage::channel() const {
  // @@protoc_insertion_point(field_get:CVImageService.ImageMessage.channel)
  return _internal_channel();
}
inline void ImageMessage::_internal_set_channel(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  channel_ = value;
}
inline void ImageMessage::set_channel(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_channel(value);
  // @@protoc_insertion_point(field_set:CVImageService.ImageMessage.channel)
}

// bytes EnCodeBuff = 6;
inline void ImageMessage::clear_encodebuff() {
  encodebuff_.ClearToEmpty();
}
inline const std::string& ImageMessage::encodebuff() const {
  // @@protoc_insertion_point(field_get:CVImageService.ImageMessage.EnCodeBuff)
  return _internal_encodebuff();
}
inline void ImageMessage::set_encodebuff(const std::string& value) {
  _internal_set_encodebuff(value);
  // @@protoc_insertion_point(field_set:CVImageService.ImageMessage.EnCodeBuff)
}
inline std::string* ImageMessage::mutable_encodebuff() {
  // @@protoc_insertion_point(field_mutable:CVImageService.ImageMessage.EnCodeBuff)
  return _internal_mutable_encodebuff();
}
inline const std::string& ImageMessage::_internal_encodebuff() const {
  return encodebuff_.Get();
}
inline void ImageMessage::_internal_set_encodebuff(const std::string& value) {
  
  encodebuff_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ImageMessage::set_encodebuff(std::string&& value) {
  
  encodebuff_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:CVImageService.ImageMessage.EnCodeBuff)
}
inline void ImageMessage::set_encodebuff(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  encodebuff_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:CVImageService.ImageMessage.EnCodeBuff)
}
inline void ImageMessage::set_encodebuff(const void* value,
    size_t size) {
  
  encodebuff_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:CVImageService.ImageMessage.EnCodeBuff)
}
inline std::string* ImageMessage::_internal_mutable_encodebuff() {
  
  return encodebuff_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ImageMessage::release_encodebuff() {
  // @@protoc_insertion_point(field_release:CVImageService.ImageMessage.EnCodeBuff)
  return encodebuff_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ImageMessage::set_allocated_encodebuff(std::string* encodebuff) {
  if (encodebuff != nullptr) {
    
  } else {
    
  }
  encodebuff_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), encodebuff,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:CVImageService.ImageMessage.EnCodeBuff)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace CVImageService

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ImageStream_2eproto
